CREATE TABLE [Staging].[Account]
(
	[Id] UNIQUEIDENTIFIER,
	[Identifier] NVARCHAR(100) NOT NULL,
	[AccountType] TINYINT NOT NULL,
	[CardOrAccountNumber] NVARCHAR(100) NULL,
	CONSTRAINT [PK_Account_Id] PRIMARY KEY NONCLUSTERED (Id ASC) WITH (DATA_COMPRESSION = PAGE),
)
